name: Deploy to Prod

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.9'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove unnecessary files
      run: |
        rm -rf ./.deployment
        rm -rf ./.devcontainer
        rm -rf ./.git*
        rm -rf ./.vscode
        rm -rf ./README.md

    - name: 'Deploy to Azure Functions'
      uses: azure/functions-action@v1.5.0
      with:
        app-name: ${{ secrets.PROD_AZURE_APP_SERVICE_NAME }}
        publish-profile: ${{ secrets.PROD_AZURE_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: ''
        enable-oryx-build: ''
